# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-glucose
Version: 0.88.0
Release: %mkrel 2
Summary: Core Sugar components
License: GPL/LGPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Requires: sugar-artwork >= 0.88.0
Requires: sugar-datastore >= 0.88.0
Requires: sugar-presence-service >= 0.88.0
Requires: sugar >= 0.88.0
Requires: sugar-base >= 0.88.0
Requires: sugar-toolkit >= 0.88.0

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
Virtual package of core Sugar components that follow the Sugarlabs
six months release schedule.
Sugar is a graphical user interface aimed at children which promotes sharing
and collaborative learning. It was introduced on the One Laptop Per Child
(OLPC) XO laptop but is useful on other devices as well.

%files
%defattr(-,root,root,-)



%changelog
* Wed Dec 08 2010 Oden Eriksson <oeriksson@mandriva.com> 0.88.0-2mdv2011.0
+ Revision: 615034
- the mass rebuild of 2010.1 packages

* Sun Apr 04 2010 Aleksey Lim <alsroot@mandriva.org> 0.88.0-1mdv2010.1
+ Revision: 531172
- Sucrose 0.88.0 release

* Mon Oct 12 2009 Aleksey Lim <alsroot@mandriva.org> 0.86.2-1mdv2010.0
+ Revision: 456971
- Push 0.86.2

* Fri Sep 25 2009 Aleksey Lim <alsroot@mandriva.org> 0.86.0-1mdv2010.0
+ Revision: 448922
- Update to 0.86.0

* Sat Sep 19 2009 Aleksey Lim <alsroot@mandriva.org> 0.85.7-1mdv2010.0
+ Revision: 444543
- Update to 0.85.7

* Tue Aug 11 2009 Aleksey Lim <alsroot@mandriva.org> 0.85.2-1mdv2010.0
+ Revision: 414887
- Sucrose 0.85.2

* Mon Apr 06 2009 Aleksey Lim <alsroot@mandriva.org> 0.84.2-1mdv2009.1
+ Revision: 364285
- Sucrose 0.84.2 release

* Sat Mar 21 2009 Aleksey Lim <alsroot@mandriva.org> 0.84.1-1mdv2009.1
+ Revision: 360050
- update version to 0.84.1

* Wed Mar 04 2009 Aleksey Lim <alsroot@mandriva.org> 0.84.0-1mdv2009.1
+ Revision: 348262
- Sucrose 0.84.0 release

* Mon Feb 23 2009 Aleksey Lim <alsroot@mandriva.org> 0.83.6-1mdv2009.1
+ Revision: 344192
- Sucrose 0.83.6 release

* Sun Feb 15 2009 Aleksey Lim <alsroot@mandriva.org> 0.83.5-1mdv2009.1
+ Revision: 340429
- new Sucrose 0.83.4 release

* Tue Jan 20 2009 Aleksey Lim <alsroot@mandriva.org> 0.83.4-1mdv2009.1
+ Revision: 331985
- new Sucrose 0.83.4 release

* Tue Jan 13 2009 Aleksey Lim <alsroot@mandriva.org> 0.83.3-1mdv2009.1
+ Revision: 328979
- make inter-glucose dependencies softer
- initial commit

