# NOTE: Do not edit, file was generated by jhconvert

Name: sugar-glucose
Version: 0.85.2
Release: %mkrel 1
Summary: Core Sugar components
License: GPL/LGPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Requires: sugar-artwork >= 0.85.2
Requires: sugar-datastore >= 0.85.1
Requires: sugar-presence-service >= 0.85.1
Requires: sugar >= 0.85.3
Requires: sugar-base >= 0.85.2
Requires: sugar-toolkit >= 0.85.3

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
Virtual package of core Sugar components that follow the Sugarlabs
six months release schedule.
Sugar is a graphical user interface aimed at children which promotes sharing
and collaborative learning. It was introduced on the One Laptop Per Child
(OLPC) XO laptop but is useful on other devices as well.

%files
%defattr(-,root,root,-)

